font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  bold:
    family: Hack Nerd Font Mono
    style: Bold

  italic:
    family: Hack Nerd Font Mono
    style: Italic

  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
size: 14

colors:

  primary:
    background: '0x1f1f1f'
    foreground: '0xc0b18b'

  normal:
    black:   '0x4a3637'
    red:     '0xd17b49'
    green:   '0x7b8748'
    yellow:  '0xaf865a'
    blue:    '0x535c5c'
    magenta: '0x775759'
    cyan:    '0x6d715e'
    white:   '0xc0b18b'

  bright:
    black:   '0x402e2e'
    red:     '0xac5d2f'
    green:   '0x647035'
    yellow:  '0x8f6840'
    blue:    '0x444b4b'
    magenta: '0x614445'
    cyan:    '0x585c49'
    white:   '0x978965'
    
cursor:
    style: Underline
background_opacity: 0.92
