#! /bin/sh

# Autostart
sxhkd &
picom &
nitrogen --restore &
flameshot &
$HOME/.config/polybar/launch.sh

# Monitors
bspc monitor HDMI-0 -d 1 2 3 4 5 6
bspc monitor DVI-D-0 -d

# BSPWM Configuration
bspc config border_width         2
bspc config window_gap           6
bspc config top_padding          0
bspc config bottom_padding       6
bspc config left_padding         6
bspc config right_padding        6
bspc config split_ratio          0.50
bspc config click_to_focus       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4d4d4d"
bspc config active_border_color	        "#F8F8F2"
bspc config focused_border_color	      "#50FA7B"
bspc config presel_feedback_color	      "#8BE9FD"
bspc config urgent_border_color 	      "#FF5555"

# Polybar Hidden When Fullscreen for VLC, Youtube, MPV ..
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-D-0)
