#! /bin/sh

# Autostart
sxhkd &
picom -bcC &
nitrogen --restore &
flameshot &
bspc wm -O HDMI-0 HDMI-1 & 
pulseaudio -D &
$HOME/.config/polybar/launch.sh

# Monitors
bspc monitor HDMI-0 -d 1 2 3 4 5 6
bspc monitor DVI-D-0 -d 1 2 3 4 5 6

# BSPWM Configuration
bspc config border_width         3
bspc config border_radius        3
bspc config window_gap           12
bspc config top_padding          6
bspc config bottom_padding       6
bspc config left_padding         6
bspc config right_padding        6
bspc config split_ratio          0.50
bspc config click_to_focus       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####

#Dracula Coloring Personal
#bspc config normal_border_color		    "#44475a"
#bspc config active_border_color	      "#f8f8f2"
#bspc config focused_border_color	    "#50fa7b"
#bspc config presel_feedback_color	    "#6272a4"
#bspc config urgent_border_color 	    "#ff6e67"

# Miramare Coloring
bspc config normal_border_color		    "#2a2426"
bspc config active_border_color	      "#d9bb80"
bspc config focused_border_color	    "#87af87"
bspc config presel_feedback_color	    "#89beba"
bspc config urgent_border_color 	    "#e68183"

#Polybar Hidden When Fullscreen for VLC, Youtube, MPV ..
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-D-0)
