" SOURCES
source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/plug-config/coc.vim
source $HOME/.config/nvim/themes/airline.vim
source $HOME/.config/nvim/plug-config/floaterm.vim
lua require'plug-colorizer'
luafile $HOME/.config/nvim/lua/plug-colorizer.lua
:let g:languagetool_jar='/usr/share/languagetool'
